{
  "students": [
    {
      "id": "student_001",
      "name": "Haruna Abubakar Liye",
      "avatar": "images/students/student_001.jpeg",
      "fullName": "Haruna Abubakar Liye",
      "nickname": "Liye",
      "address": "Tudun Murtala",
      "phone": "+2348142414843",
      "email": "harunaliye19@gmail.com",
      "ambition": "Data Analyst",
      "graduationDate": "Oct-25",
      "specialization": "Data Analyst"
    },
    {
      "id": "student_002",
      "name": "Muhammad Muddassir Lawan",
      "avatar": "images/students/student_002.jpeg",
      "fullName": "Muhammad Muddassir lawan",
      "nickname": "Muddassir",
      "address": "Gwarzo Zango kanti",
      "phone": "+2349122500822",
      "email": "muhdmuddassirlawan633@gmail.com",
      "ambition": "Programmer",
      "graduationDate": "Oct-25",
      "specialization": "Programmer"
    },
    {
      "id": "student_003",
      "name": "Abdul Ali Lawan",
      "avatar": "images/students/student_003.jpeg",
      "fullName": "ABDUL ALI LAWAN",
      "nickname": "ABDUL",
      "address": "No 126 sagagi quarters",
      "phone": "+2348162386946",
      "email": "abdulalilawan90@gmail.com",
      "ambition": "OFFICER (NIGERIAN NAVY)",
      "graduationDate": "Oct-25",
      "specialization": "OFFICER (NIGERIAN NAVY)"
    },
    {
      "id": "student_004",
      "name": "Bello Suyudi Adam",
      "avatar": "images/students/student_004.jpeg",
      "fullName": "Bello Suyudi Adam",
      "nickname": "Me Cape",
      "address": "No 326 Jaen Gidan Dagachi Sharada phase 3",
      "phone": "+2349022628630",
      "email": "bellosuyudi97@gmail.com",
      "ambition": "To being a politician and also Entrepreneur too",
      "graduationDate": "Oct-25",
      "specialization": "To being a politician and also Entrepreneur too"
    },
    {
      "id": "student_005",
      "name": "Sani Adamu Yunusa",
      "avatar": "images/students/student_005.jpeg",
      "fullName": "Sani Adamu Yunusa",
      "nickname": "Sanityboy",
      "address": "No 104 Dorayi CRC Gabas",
      "phone": "+2349024003431",
      "email": "yunusasani1996@gmail.com",
      "ambition": "Web Development",
      "graduationDate": "Oct-25",
      "specialization": "Web Development"
    },
    {
      "id": "student_006",
      "name": "Adebisi Adijat Abidemi",
      "avatar": "images/students/student_006.jpeg",
      "fullName": "Adebisi Adijat Abidemi",
      "nickname": "Triple A",
      "address": "Rangaza rimi Dan Maliki,kano",
      "phone": "+2347068432282",
      "email": "adebisiadijat444@gmail.com",
      "ambition": "Entrepreneur",
      "graduationDate": "Oct-25",
      "specialization": "Entrepreneur"
    },
    {
      "id": "student_007",
      "name": "Muhammad Abubakar",
      "avatar": "images/students/student_007.jpeg",
      "fullName": "Muhammad Abubakar",
      "nickname": "DADDY JR",
      "address": "Hotoro tinshama No.229",
      "phone": "+2348029120562",
      "email": "muhdjajeri5@outlook.com",
      "ambition": "Entrepreneur",
      "graduationDate": "Oct-25",
      "specialization": "Entrepreneur"
    },
    {
      "id": "student_008",
      "name": "Husaini Muhammad",
      "avatar": "images/students/student_008.jpeg",
      "fullName": "HUSAINI MUHAMMAD",
      "nickname": "HUSSEIN",
      "address": "No: 1A gwammaja layin kwango",
      "phone": "+2348143620866",
      "email": "husainimuhd2003@gmail.com",
      "ambition": "IMMIGRATION OFFICER",
      "graduationDate": "Oct-25",
      "specialization": "IMMIGRATION OFFICER"
    },
    {
      "id": "student_009",
      "name": "Comfort Adamu Ali",
      "avatar": "images/students/student_009.jpeg",
      "fullName": "COMFORT ADAMU ALI",
      "nickname": "Comfort Adams",
      "address": "Farawa Along Maiduguri Road, Kano.",
      "phone": "+2349037941671",
      "email": "adamscomfort70@gmail.com",
      "ambition": "Data Scientist",
      "graduationDate": "Oct-25",
      "specialization": "Data Scientist"
    },
    {
      "id": "student_010",
      "name": "Haris Haris Adam",
      "avatar": "images/students/student_010.jpeg",
      "fullName": "HARIS HARIS ADAM",
      "nickname": "Khalifso",
      "address": "Rijiyar lemo titin dogon bene fagge L.G",
      "phone": "+2348164222942",
      "email": "harisadamharis64@gmail.com",
      "ambition": "Millionaire",
      "graduationDate": "Oct-25",
      "specialization": "Millionaire"
    },
    {
      "id": "student_011",
      "name": "Halima Sani Lawan",
      "avatar": "images/students/student_011.jpeg",
      "fullName": "Halima Sani Lawan",
      "nickname": "Arfah",
      "address": "Block FM 131 Housing Estate Zoo Road",
      "phone": "+2349015237325",
      "email": "info.halimasanilawan@gmail.com",
      "ambition": "Voiceover Artist",
      "graduationDate": "Oct-25",
      "specialization": "Voiceover Artist"
    },
    {
      "id": "student_012",
      "name": "Saminu Ismail Kademi",
      "avatar": "images/students/student_012.jpeg",
      "fullName": "Saminu Ismail kademi",
      "nickname": "Kademi",
      "address": "Gaya Local government area kademi city",
      "phone": "+2347062554890",
      "email": "saminuismailkademi@gmail.com",
      "ambition": "An entrepreneur",
      "graduationDate": "Oct-25",
      "specialization": "An entrepreneur"
    },
    {
      "id": "student_013",
      "name": "Zainab Salihu Maikarfi",
      "avatar": "images/students/student_013.jpeg",
      "fullName": "Zainab salihu Maikarfi",
      "nickname": "Zee Maikarfi",
      "address": "No:53 Nai'bawa Yan-lemo",
      "phone": "+2348130820424",
      "email": "zsalihumaikarfi@gmail.com",
      "ambition": "developer",
      "graduationDate": "Oct-25",
      "specialization": "developer"
    },
    {
      "id": "student_014",
      "name": "Sadik Badayi Abba",
      "avatar": "images/students/student_014.jpeg",
      "fullName": "Sadik Badayi Abba",
      "nickname": "Abba",
      "address": "Gwangwazo",
      "phone": "+2347068300407",
      "email": "sadeeqbadayiabba@gmail.com",
      "ambition": "Mother happiness",
      "graduationDate": "Oct-25",
      "specialization": "Mother happiness"
    },
    {
      "id": "student_015",
      "name": "Mannir Iliyasu Yusuf",
      "avatar": "images/students/student_015.jpeg",
      "fullName": "Mannir iliyasu yusuf",
      "nickname": "Dankolin Bichi",
      "address": "Gwammaja Layin kankare, Bichi Sabon Layi kanti, Gidan yankoli.",
      "phone": "+2348100215575",
      "email": "mannirilyasuyusuf@gmail.com",
      "ambition": "Politician, web developer.",
      "graduationDate": "Oct-25",
      "specialization": "Politician, web developer."
    },
    {
      "id": "student_016",
      "name": "Hafsa Musa Hassan",
      "avatar": "images/students/student_016.jpeg",
      "fullName": "Hafsa Musa Hassan",
      "nickname": "",
      "address": "Zawaciki housing estate",
      "phone": "+2348136935446",
      "email": "hafsatmusahassan88@gmail.com",
      "ambition": "Entrepreneur and also web Developer",
      "graduationDate": "Oct-25",
      "specialization": "Entrepreneur and also web Developer"
    },
    {
      "id": "student_017",
      "name": "Aisha Musa Isah",
      "avatar": "images/students/student_017.jpeg",
      "fullName": "Aisha Musa Isah",
      "nickname": "Dagash",
      "address": "1551 Isah kaita Street by zoo Road",
      "phone": "+2340904 251 4152",
      "email": "aishamusaisah34@gmail.com",
      "ambition": "Web developer",
      "graduationDate": "Oct-25",
      "specialization": "Web developer"
    },
    {
      "id": "student_018",
      "name": "Umar Mukhtar Umar",
      "avatar": "images/students/student_018.jpeg",
      "fullName": "UMAR MUKHTAR UMAR",
      "nickname": "OUMAR (PRESIDOR)",
      "address": "DUKAWA NO:202 QUATERS KANO MUNICIPAL",
      "phone": "+2349033831059",
      "email": "umarmukhtarumar6@gmail.com",
      "ambition": "ENTREPRENEUR",
      "graduationDate": "Oct-25",
      "specialization": "ENTREPRENEUR"
    },
    {
      "id": "student_019",
      "name": "Abubakar Abdullahi Salisu",
      "avatar": "images/students/student_019.jpeg",
      "fullName": "Abubakar Abdullahi Salisu",
      "nickname": "Abubakar AS (Rano)",
      "address": "Kwana Street, Tsohon Gari, Rano.",
      "phone": "+2349037209945",
      "email": "aburano2022@gmail.com",
      "ambition": "Naval Officer",
      "graduationDate": "Oct-25",
      "specialization": "Naval Officer"
    },
    {
      "id": "student_020",
      "name": "Adam Muhammad Abdullahi",
      "avatar": "images/students/student_020.jpeg",
      "fullName": "ADAM MUHAMMAD ABDULLAHI",
      "nickname": "AMAS",
      "address": "Kano municipal",
      "phone": "+2347046399785",
      "email": "mramass1234@gmail.com",
      "ambition": "CEO",
      "graduationDate": "Oct-25",
      "specialization": "CEO"
    },
    {
      "id": "student_021",
      "name": "Fatima Ahmad Bayero",
      "avatar": "images/students/student_021.jpeg",
      "fullName": "Fatima Ahmad Bayero",
      "nickname": "Yasmeen",
      "address": "Janbulo2gate",
      "phone": "+2348132621762",
      "email": "fatimabayeroahmad@gmail.com",
      "ambition": "Entrepreneur",
      "graduationDate": "Oct-25",
      "specialization": "Entrepreneur"
    },
    {
      "id": "student_022",
      "name": "Mansur Auwalu Mijinyawa",
      "avatar": "images/students/student_022.jpeg",
      "fullName": "Mansur Auwalu Mijinyawa",
      "nickname": "Werleed",
      "address": "Dan Agundi Road",
      "phone": "+2349066695074",
      "email": "mansuramijinyawa@gmail.com",
      "ambition": "Entrepreneur",
      "graduationDate": "Oct-25",
      "specialization": "Entrepreneur"
    },
    {
      "id": "student_023",
      "name": "Faruq Mahraz",
      "avatar": "images/students/student_023.jpeg",
      "fullName": "Faruq mahraz",
      "nickname": "Sniper",
      "address": "No 74 sabaru kawaji kano",
      "phone": "+2348065871957",
      "email": "Farukmahraz2011@gmail.com",
      "ambition": "Politician",
      "graduationDate": "Oct-25",
      "specialization": "Politician"
    },
    {
      "id": "student_024",
      "name": "Aisha Yusuf",
      "avatar": "images/students/student_024.jpeg",
      "fullName": "AIsha yusuf",
      "nickname": "Eeeshert",
      "address": "Brigade",
      "phone": "+2348134150403",
      "email": "aysheryusuf74@gmail.com",
      "ambition": "WEB DEVELOPER",
      "graduationDate": "Oct-25",
      "specialization": "WEB DEVELOPER"
    },
    {
      "id": "student_025",
      "name": "Muhammad Abdulkadir Usman",
      "avatar": "images/students/student_025.jpeg",
      "fullName": "Muhammad Abdulkadir usman",
      "nickname": "kwalli",
      "address": "Kwalli unguwar gini No 267",
      "phone": "+2349018432002",
      "email": "muhammadabdulkadirusman3@gmail.com",
      "ambition": "Kwalli Oil & Gas Nigerian limited",
      "graduationDate": "Oct-25",
      "specialization": "Kwalli Oil & Gas Nigerian limited"
    },
    {
      "id": "student_026",
      "name": "Sadiq Baba Salihu",
      "avatar": "images/students/student_026.jpeg",
      "fullName": "Sadiq Baba Salihu",
      "nickname": "Danbaba",
      "address": "No 107 Hausawa Galadanci Gwale Local Government Kano State",
      "phone": "+2347034585168",
      "email": "Sdanbaba2000@gmail.com",
      "ambition": "Entrepreneur",
      "graduationDate": "Oct-25",
      "specialization": "Entrepreneur"
    },
    {
      "id": "student_027",
      "name": "Mujiburrahman Mujittapha Idris Yakasai",
      "avatar": "images/students/student_027.jpeg",
      "fullName": "Mujiburrahman Mujittapha Idris Yakasai",
      "nickname": "Mujeebu Goma",
      "address": "No 66 Yakasai B, kano Municipal Local Government Area, Kano State",
      "phone": "+2349033997383",
      "email": "Mujiburrahman3399@gmail.com",
      "ambition": "Web Developer",
      "graduationDate": "Oct-25",
      "specialization": "Web Developer"
    },
    {
      "id": "student_028",
      "name": "Bashir Umar Dahiru",
      "avatar": "images/students/student_028.jpeg",
      "fullName": "BASHIR UMAR DAHIRU",
      "nickname": "BIN OUMAR 001",
      "address": "No 875 Gama B Layin Goruba",
      "phone": "+2348062218105",
      "email": "bashirumardahiru2022@gmail.com",
      "ambition": "Web developer",
      "graduationDate": "Oct-25",
      "specialization": "Web developer"
    },
    {
      "id": "student_029",
      "name": "Usman Shehu Abdullahi",
      "avatar": "images/students/student_029.jpeg",
      "fullName": "Usman Shehu Abdullahi",
      "nickname": "Coach",
      "address": "Danladi Nasidi Housing Estates",
      "phone": "+2348133708030",
      "email": "usmanshehu320@gmail.com",
      "ambition": "Web Developer",
      "graduationDate": "Oct-25",
      "specialization": "Web Developer"
    },
    {
      "id": "student_030",
      "name": "Zainab",
      "avatar": "images/students/student_030.jpeg",
      "fullName": "Zainab",
      "nickname": "Zeezee sparkles",
      "address": "Km 8 Hadeja road tokarawa",
      "phone": "+2349010931949",
      "email": "zainabusmanibrahim993@gmail.com",
      "ambition": "Entrepreneur",
      "graduationDate": "Oct-25",
      "specialization": "Entrepreneur"
    },
    {
      "id": "student_031",
      "name": "Aisha Jaafar Kulo",
      "avatar": "images/students/student_031.jpeg",
      "fullName": "Aisha Jaafar Kulo",
      "nickname": "Amieeratou kulo",
      "address": "Yankaba",
      "phone": "+2349063983380",
      "email": "aishajaafar777@gmail.com",
      "ambition": "Web Developer",
      "graduationDate": "Oct-25",
      "specialization": "Web Developer"
    },
    {
      "id": "student_032",
      "name": "Aisha Yusuf Salihu",
      "avatar": "images/students/student_032.jpeg",
      "fullName": "Aisha Yusuf Salihu",
      "nickname": "Humairah",
      "address": "Dorayi Babba Yamadawa",
      "phone": "+2348128021725",
      "email": "humairayusuf16@gmail.com",
      "ambition": "Web Developer",
      "graduationDate": "Oct-25",
      "specialization": "Web Developer"
    },
    {
      "id": "student_033",
      "name": "Hassan Tijjani Hassan",
      "avatar": "images/students/student_033.jpeg",
      "fullName": "Hassan Tijjani Hassan",
      "nickname": "Khalifa",
      "address": "Sharada",
      "phone": "+2348148242446",
      "email": "hassantijjani2446@gmail.com",
      "ambition": "â€¦.",
      "graduationDate": "Oct-25",
      "specialization": "â€¦."
    },
    {
      "id": "student_034",
      "name": "Shamsu Isyaku Ali",
      "avatar": "images/students/student_034.jpeg",
      "fullName": "Shamsu isyaku ali",
      "nickname": "S,KHAN",
      "address": "No 214 zage quters",
      "phone": "+2347010005532",
      "email": "Shamsuisyakuali@gmail.com",
      "ambition": "Politician",
      "graduationDate": "Oct-25",
      "specialization": "Politician"
    },
    {
      "id": "student_035",
      "name": "Hussain Adamu Saleh",
      "avatar": "images/students/student_035.jpeg",
      "fullName": "Hussain Adamu saleh",
      "nickname": "Hussain",
      "address": "Sheka sabuwar abuja",
      "phone": "+2348082408858",
      "email": "Hussainadamsaleh17@gmail.com",
      "ambition": "Nigerian president",
      "graduationDate": "Oct-25",
      "specialization": "Nigerian president"
    },
    {
      "id": "student_036",
      "name": "Isah Abdullahi Isah",
      "avatar": "images/students/student_036.jpeg",
      "fullName": "ISAH ABDULLAHI ISAH",
      "nickname": "Sir",
      "address": "No. 8 Zuwa Avenue, Gadon Kaya",
      "phone": "+2348167928397",
      "email": "eesabba856@gmail.com",
      "ambition": "Software Engineer",
      "graduationDate": "Oct-25",
      "specialization": "Software Engineer"
    },
    {
      "id": "student_037",
      "name": "Beloo Sani Bello",
      "avatar": "images/students/student_037.jpeg",
      "fullName": "Beloo Sani Bello",
      "nickname": "B.S.B_YOLA (HEJI)",
      "address": "No18&19 Blue Avenue Zawachiki Gida dubu",
      "phone": "+2348128861334",
      "email": "bsbyola@gmail.com",
      "ambition": "Business man& Web developer",
      "graduationDate": "Oct-25",
      "specialization": "Business man& Web developer"
    },
    {
      "id": "student_038",
      "name": "Amir Bashir Lawan",
      "avatar": "images/students/student_038.jpeg",
      "fullName": "AMIR BASHIR LAWAN",
      "nickname": "",
      "address": "Rijiyar Lemo",
      "phone": "+2347037477183",
      "email": "amirbashirlawan@gmail.com",
      "ambition": "Entrepreneur",
      "graduationDate": "Oct-25",
      "specialization": "Entrepreneur"
    },
    {
      "id": "student_039",
      "name": "Abubakar Sani Abdullahi",
      "avatar": "images/students/student_039.jpeg",
      "fullName": "Abubakar Sani Abdullahi",
      "nickname": "Sadeeq",
      "address": "Kura Muhd Street Yankaba Kano",
      "phone": "+2349036960513",
      "email": "Saniabubakar874@gmail.com",
      "ambition": "Software Developer",
      "graduationDate": "Oct-25",
      "specialization": "Software Developer"
    },
    {
      "id": "student_040",
      "name": "Ismail Ibrahim Idris",
      "avatar": "images/students/student_040.jpeg",
      "fullName": "Ismail Ibrahim Idris",
      "nickname": "Famous6tar",
      "address": "No. 114 Kurna Asabe B",
      "phone": "+2347066898030",
      "email": "famous6tar@gmail.com",
      "ambition": "IT Consultant",
      "graduationDate": "Oct-25",
      "specialization": "IT Consultant"
    },
    {
      "id": "student_041",
      "name": "Rasheedat Abdulazeez",
      "avatar": "images/students/student_041.jpeg",
      "fullName": "Rasheedat Abdulazeez",
      "nickname": "Oum Muslimah",
      "address": "Ladanai Hotoro Arewa",
      "phone": "+2348160532913",
      "email": "rasheedatabdulazeez01@gmail.com",
      "ambition": "Web Developer",
      "graduationDate": "Oct-25",
      "specialization": "Web Developer"
    },
    {
      "id": "student_042",
      "name": "Ibrahim Umar Madugu",
      "avatar": "images/students/student_042.jpeg",
      "fullName": "IBRAHIM UMAR MADUGU",
      "nickname": "MADUGU",
      "address": "RIJIYAR ZAKI QTRS.",
      "phone": "+2347066309396",
      "email": "ibrahimumarmadugu15@gmail.com",
      "ambition": "ETHICAL HACKING",
      "graduationDate": "Oct-25",
      "specialization": "ETHICAL HACKING"
    },
    {
      "id": "student_043",
      "name": "Maryam Magaji Saleh",
      "avatar": "images/students/student_043.jpeg",
      "fullName": "Maryam Magaji Saleh",
      "nickname": "MARFAT",
      "address": "No.100 hotoro north,c/gari",
      "phone": "+2349035101066",
      "email": "maryammagaji3510@gmail.com",
      "ambition": "Web developer",
      "graduationDate": "Oct-25",
      "specialization": "Web developer"
    }
  ]
}